### ISSUE TITLE
Output more descriptive error messages

### ISSUE THREAD

**Issue by DinuNuggets** [veigamann/sydney-whatsapp-chatbot#7] opened 2023-05-18 08:28 UTC
Sometimes I get this error message from the bot in WhatsApp:
```
Error when answering this message.

Details: {}
```
There is nothing in the console about this

**Comment by veigamann** [comment] 2023-05-18 11:05
I've also noticed this, which is likely caused by the unresolved or erroring promise sent to Bing. I'll work on fixing it or at least providing a clearer error message to the user.

**Comment by DinuNuggets** [comment] 2023-05-18 14:10
If that happens, I simply repeat my text until it works. 
Could it be done in a way that the prompt is sent repeatedly automatically until it works?

**Comment by arnab3k** [comment] 2023-05-18 17:58
Error when answering this message.

Details: {}

I still have not got it to work even once lol

**Comment by veigamann** [comment] 2023-06-01 02:37
Fixed in 8886f72.

**Closed by veigamann** 2023-06-01 02:37 UTC
Labels: bug, feature/enhancement, high priority
